// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhb6UuDRtgiayoVckP80Skgd626sdDYX0',
    appId: '1:965508492160:web:3bc4f5f0271dfdd69d2f65',
    messagingSenderId: '965508492160',
    projectId: 'cbo-joblist-mobileapp',
    authDomain: 'cbo-joblist-mobileapp.firebaseapp.com',
    storageBucket: 'cbo-joblist-mobileapp.firebasestorage.app',
    measurementId: 'G-K7HKH94W9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOxkB4soUR9OxyaUt-dgYNHxJPGWjzeyA',
    appId: '1:965508492160:android:a3cfceec58aad6c39d2f65',
    messagingSenderId: '965508492160',
    projectId: 'cbo-joblist-mobileapp',
    storageBucket: 'cbo-joblist-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4zjzuq9i76oC9xSrzEhRBXak-Va_Nkus',
    appId: '1:965508492160:ios:673f097a341643849d2f65',
    messagingSenderId: '965508492160',
    projectId: 'cbo-joblist-mobileapp',
    storageBucket: 'cbo-joblist-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.cboMobileAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4zjzuq9i76oC9xSrzEhRBXak-Va_Nkus',
    appId: '1:965508492160:ios:673f097a341643849d2f65',
    messagingSenderId: '965508492160',
    projectId: 'cbo-joblist-mobileapp',
    storageBucket: 'cbo-joblist-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.cboMobileAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhb6UuDRtgiayoVckP80Skgd626sdDYX0',
    appId: '1:965508492160:web:8389df675d68a75a9d2f65',
    messagingSenderId: '965508492160',
    projectId: 'cbo-joblist-mobileapp',
    authDomain: 'cbo-joblist-mobileapp.firebaseapp.com',
    storageBucket: 'cbo-joblist-mobileapp.firebasestorage.app',
    measurementId: 'G-FGEVRVXQ69',
  );
}
